<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1dbffe38-3822-49d0-94d3-e983dba0fcea</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StoreApp.Data\StoreApp.Data.csproj" />
    <ProjectReference Include="..\StoreApp.Mappers\StoreApp.Mappers.csproj" />
    <ProjectReference Include="..\StoreApp.Repositories\StoreApp.Repositories.csproj" />
    <ProjectReference Include="..\StoreApp.UseCases\StoreApp.UseCases.csproj" />
  </ItemGroup>

</Project>
